"""Phase1 P0 full schema (19 tables)

Revision ID: 827c44be1b80
Revises: 020389f690df
Create Date: 2026-08-23 16:09:49.859243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827c44be1b80'
down_revision: Union[str, Sequence[str], None] = '020389f690df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date_rule',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False, comment='year-only / year-month / 上旬 / 中旬 / 下旬 / ...'),
    sa.Column('resolve', sa.String(), nullable=False, comment='12-30 / 月底 / 1日 / ...'),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern', name='uq_date_rule_pattern')
    )
    op.create_table('entity',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True, comment='公司状态（仅 company；只增不减）'),
    sa.Column('fields', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_line', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('version_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("entity_type IN ('person','company','asset','family')", name='ck_entity_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'name', name='uq_entity_type_name')
    )
    op.create_table('exchange_rate',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fx_from', sa.String(), nullable=False),
    sa.Column('fx_to', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True, comment='NULL=基准折算率常量'),
    sa.Column('rate', sa.Numeric(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_line', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(), nullable=False, comment='欧洲/英国/美国/香港/中国'),
    sa.Column('risk_lvl', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.CheckConstraint("risk_lvl IN ('R1','R2','R3','R4','R5')", name='ck_investment_risk'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'region', name='uq_investment_year_region')
    )
    op.create_table('recompute_job',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('files', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','running','done','failed')", name='ck_recompute_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('return_curve',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('risk_lvl', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(), nullable=True, comment='年化收益 %（如 21.7）'),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_line', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("risk_lvl IN ('R1','R2','R3','R4','R5')", name='ck_return_risk'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country', 'risk_lvl', 'year', name='uq_return_country_risk_year')
    )
    op.create_table('snapshot',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('as_of_year', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=True, comment='date 级游标；NULL=仅年聚合'),
    sa.Column('scope', sa.String(), nullable=False, comment="'account:12:BEF' / 'entity:3' / 'family:total'"),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snap_years', 'snapshot', ['as_of_year'], unique=False)
    op.create_index('ux_snap_date', 'snapshot', ['as_of_date', 'scope'], unique=True, postgresql_where=sa.text('as_of_date IS NOT NULL'))
    op.create_index('ux_snap_year', 'snapshot', ['as_of_year', 'scope'], unique=True, postgresql_where=sa.text('as_of_date IS NULL'))
    op.create_table('source_file_version',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path', 'version', name='uq_sfv_path_version')
    )
    op.create_table('timeline_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_year', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('decade', sa.String(), nullable=True),
    sa.Column('overlay', sa.Boolean(), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_line', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timeline_year', 'timeline_event', ['event_year'], unique=False)
    op.create_table('user_data_overlay',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('section', sa.String(), nullable=False, comment="'timeline' 等"),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('closed_on', sa.Date(), nullable=True),
    sa.Column('migrate_to_currency', sa.String(), nullable=True),
    sa.Column('bank', sa.String(), nullable=True),
    sa.CheckConstraint("status IN ('active','closed')", name='ck_account_status'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'currency', 'bank', name='uq_account_entity_currency_bank')
    )
    op.create_table('finance_entry',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_kind', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_line', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("kind IN ('income','expense','investment','investment_income','pool')", name='ck_finance_kind'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holding_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True, comment='buy/sell/split/acquire-cash/acquire-share'),
    sa.Column('batch_id', sa.BigInteger(), nullable=True, comment='成本批次；FIFO 卖出扣成本'),
    sa.Column('shares', sa.Numeric(), nullable=True),
    sa.Column('unit_price', sa.Numeric(), nullable=True, comment='该批次成本价（FIFO）'),
    sa.Column('amount', sa.Numeric(), nullable=True, comment='单位：万美金'),
    sa.Column('pct', sa.Numeric(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_line', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_holding_entity', 'holding_event', ['entity_id', 'company'], unique=False)
    op.create_table('income_stream',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('stream_type', sa.String(), nullable=False),
    sa.Column('group_key', sa.String(), nullable=True, comment='属地/地域颗粒'),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False, comment='文件写死的金额/税后值，直接入账'),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_line', sa.Integer(), nullable=True),
    sa.CheckConstraint("stream_type IN ('rent','property','security','shop','salary')", name='ck_income_stream_type'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('initial_asset',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('group_key', sa.String(), nullable=True, comment="股票债券同域打包颗粒（如 '丹麦股票债券'）"),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('face_value', sa.Numeric(), nullable=True),
    sa.Column('pct', sa.Numeric(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_line', sa.Integer(), nullable=True),
    sa.CheckConstraint("asset_type IN ('cash','bond','stock','property')", name='ck_initial_asset_type'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment_alloc',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('investment_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('is_all', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['investment_id'], ['investment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['recompute_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationship',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('from_entity_id', sa.BigInteger(), nullable=False),
    sa.Column('to_entity_id', sa.BigInteger(), nullable=False),
    sa.Column('rel_type', sa.String(), nullable=False, comment='parent/child/member/holds/acquired/split'),
    sa.Column('since_year', sa.Integer(), nullable=True),
    sa.Column('until_year', sa.Integer(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_line', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['from_entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['to_entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledger_entry',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('inflow', sa.Numeric(), nullable=True),
    sa.Column('outflow', sa.Numeric(), nullable=True),
    sa.Column('balance', sa.Numeric(), nullable=True, comment='余额（schema 存源值；重算校验连续）'),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_line', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("kind IN ('income','expense','investment','investment_income','pool')", name='ck_ledger_kind'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_acct_date', 'ledger_entry', ['account_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ledger_acct_date', table_name='ledger_entry')
    op.drop_table('ledger_entry')
    op.drop_table('relationship')
    op.drop_table('notification')
    op.drop_table('investment_alloc')
    op.drop_table('initial_asset')
    op.drop_table('income_stream')
    op.drop_index('ix_holding_entity', table_name='holding_event')
    op.drop_table('holding_event')
    op.drop_table('finance_entry')
    op.drop_table('account')
    op.drop_table('user_data_overlay')
    op.drop_index('ix_timeline_year', table_name='timeline_event')
    op.drop_table('timeline_event')
    op.drop_table('source_file_version')
    op.drop_index('ux_snap_year', table_name='snapshot', postgresql_where=sa.text('as_of_date IS NULL'))
    op.drop_index('ux_snap_date', table_name='snapshot', postgresql_where=sa.text('as_of_date IS NOT NULL'))
    op.drop_index('ix_snap_years', table_name='snapshot')
    op.drop_table('snapshot')
    op.drop_table('return_curve')
    op.drop_table('recompute_job')
    op.drop_table('investment')
    op.drop_table('exchange_rate')
    op.drop_table('entity')
    op.drop_table('date_rule')
    # ### end Alembic commands ###
